### PR TITLE
typos

### PR DESCRIPTION
**Pull request by charleskimbac**

### CODE REVIEW

**Review by bjb211 — CHANGES_REQUESTED** [review]
tilde is the correct spelling

**Comment by charleskimbac** [comment]
it's changed to tilde no?

**Comment by bjb211** [comment]
> 

Yes, sorry. I looked at it backwards. :)

**Comment by bjb211** [comment]
> it's changed to tilde no?

I really appreciate you taking the time to make these changes.

**Comment by charleskimbac** [comment]
ofc, no problem; i love fixing stuff like typos, however unusual it is

**Pull request merged**
